In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls "/content/drive/MyDrive/"

'Colab Notebooks'  'Copy of BikeIndia.csv'  'NEW DOCS.zip'

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Copy of BikeIndia.csv')
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [ ]:
df.head(20)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
5,6,06-01-2018,1,0,1,0,4,1,1,8.378268,11.66045,51.8261,6.000868,88,1518,1606
6,7,07-01-2018,1,0,1,0,5,1,2,8.057402,10.44195,49.8696,11.304642,148,1362,1510
7,8,08-01-2018,1,0,1,0,6,0,2,6.765000,8.11270,53.5833,17.875868,68,891,959
8,9,09-01-2018,1,0,1,0,0,0,1,5.671653,5.80875,43.4167,24.250650,54,768,822
9,10,10-01-2018,1,0,1,0,1,1,1,6.184153,7.54440,48.2917,14.958889,41,1280,1321
10,11,11-01-2018,1,0,1,0,2,1,2,6.932731,9.57320,68.6364,8.182844,43,1220,1263
11,12,12-01-2018,1,0,1,0,3,1,1,7.081807,8.02365,59.9545,20.410009,25,1137,1162
12,13,13-01-2018,1,0,1,0,4,1,1,6.765000,7.54415,47.0417,20.167000,38,1368,1406
13,14,14-01-2018,1,0,1,0,5,1,1,6.595670,9.42065,53.7826,8.478716,54,1367,1421
14,15,15-01-2018,1,0,1,0,6,0,2,9.566653,12.40560,49.8750,10.583521,222,1026,1248
15,16,16-01-2018,1,0,1,0,0,0,1,9.498347,11.71085,48.3750,12.625011,251,953,1204
16,17,17-01-2018,1,0,1,1,1,0,2,7.209153,8.83855,53.7500,12.999139,117,883,1000
17,18,18-01-2018,1,0,1,0,2,1,2,8.883347,11.61665,86.1667,9.833925,9,674,683
18,19,19-01-2018,1,0,1,0,3,1,2,11.979134,14.92110,74.1739,13.957239,78,1572,1650
19,20,20-01-2018,1,0,1,0,4,1,2,10.728347,12.75250,53.8333,13.125568,83,1844,1927

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     730 non-null    int64
 1   dteday      730 non-null    object
 2   season      730 non-null    int64
 3   yr          730 non-null    int64
 4   mnth        730 non-null    int64
 5   holiday     730 non-null    int64
 6   weekday     730 non-null    int64
 7   workingday  730 non-null    int64
 8   weathersit  730 non-null    int64
 9   temp        730 non-null    float64
 10  atemp       730 non-null    float64
 11  hum         730 non-null    float64
 12  windspeed   730 non-null    float64
 13  casual      730 non-null    int64
 14  registered  730 non-null    int64
 15  cnt         730 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.4+ KB

In [ ]:
df.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000
mean,365.500000,2.498630,0.500000,6.526027,0.028767,2.997260,0.683562,1.394521,20.319259,23.726322,62.765175,12.763620,849.249315,3658.757534,4508.006849
std,210.877136,1.110184,0.500343,3.450215,0.167266,2.006161,0.465405,0.544807,7.506729,8.150308,14.237589,5.195841,686.479875,1559.758728,1936.011647
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.424346,3.953480,0.000000,1.500244,2.000000,20.000000,22.000000
25%,183.250000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,13.811885,16.889713,52.000000,9.041650,316.250000,2502.250000,3169.750000
50%,365.500000,3.000000,0.500000,7.000000,0.000000,3.000000,1.000000,1.000000,20.465826,24.368225,62.625000,12.125325,717.000000,3664.500000,4548.500000
75%,547.750000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,26.880615,30.445775,72.989575,15.625589,1096.500000,4783.250000,5966.000000
max,730.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,35.328347,42.044800,97.250000,34.000021,3410.000000,6946.000000,8714.000000

In [ ]:
type(df[['yr']])

pandas.core.frame.DataFrame

In [ ]:
df.loc[2:6,['windspeed','registered']]

   windspeed  registered
2  16.636703        1229
3  10.739832        1454
4  12.522300        1518
5   6.000868        1518
6  11.304642        1362

In [ ]:
df.set_index('instant',inplace = True)

In [ ]:
df.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [ ]:
df.loc[2:6,['windspeed','registered']]

         windspeed  registered
instant
2        16.652113         670
3        16.636703        1229
4        10.739832        1454
5        12.522300        1518
6         6.000868        1518

In [ ]:
df.reset_index()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
726,727,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [ ]:
df2 = df[df['windspeed']>10][['windspeed','atemp','temp','hum']]
df2.head()

         windspeed     atemp       temp      hum
instant
1        10.749882  18.18125  14.110847  80.5833
2        16.652113  17.68695  14.902598  69.6087
3        16.636703   9.47025   8.050924  43.7273
4        10.739832  10.60610   8.200000  59.0435
5        12.522300  11.46350   9.305237  43.6957

In [ ]:
df2

         windspeed     atemp       temp      hum
instant
1        10.749882  18.18125  14.110847  80.5833
2        16.652113  17.68695  14.902598  69.6087
3        16.636703   9.47025   8.050924  43.7273
4        10.739832  10.60610   8.200000  59.0435
5        12.522300  11.46350   9.305237  43.6957
...            ...       ...        ...      ...
725      21.208582  11.01665   9.976653  82.3333
726      23.458911  11.33210  10.420847  65.2917
727      10.416557  12.75230  10.386653  59.0000
729      23.500518  11.58500  10.489153  48.3333
730      10.374682  11.17435   8.849153  57.7500

[488 rows x 4 columns]

In [ ]:
df2.shape

(488, 4)

In [ ]:
df3 = pd.merge(df,df2,how='inner',on= ['temp','atemp'])
df3.shape

(489, 17)

In [ ]:
df3

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum_x,windspeed_x,casual,registered,cnt,windspeed_y,hum_y
0,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985,10.749882,80.5833
1,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801,16.652113,69.6087
2,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,16.636703,43.7273
3,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,10.739832,59.0435
4,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,12.522300,43.6957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,26-12-2019,1,1,12,0,3,1,3,9.976653,11.01665,82.3333,21.208582,9,432,441,21.208582,82.3333
485,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114,23.458911,65.2917
486,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095,10.416557,59.0000
487,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796,23.500518,48.3333
488,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729,10.374682,57.7500

In [ ]:
df

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
727,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
728,29-12-2019,1,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
729,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
730,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489 entries, 0 to 488
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   dteday       489 non-null    object
 1   season       489 non-null    int64
 2   yr           489 non-null    int64
 3   mnth         489 non-null    int64
 4   holiday      489 non-null    int64
 5   weekday      489 non-null    int64
 6   workingday   489 non-null    int64
 7   weathersit   489 non-null    int64
 8   temp         489 non-null    float64
 9   atemp        489 non-null    float64
 10  hum_x        489 non-null    float64
 11  windspeed_x  489 non-null    float64
 12  casual       489 non-null    int64
 13  registered   489 non-null    int64
 14  cnt          489 non-null    int64
 15  windspeed_y  489 non-null    float64
 16  hum_y        489 non-null    float64
dtypes: float64(6), int64(10), object(1)
memory usage: 65.1+ KB

In [ ]:
df4=pd.concat(axis=0,objs=[df,df2])

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1218 entries, 1 to 730
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dteday      730 non-null    object
 1   season      730 non-null    float64
 2   yr          730 non-null    float64
 3   mnth        730 non-null    float64
 4   holiday     730 non-null    float64
 5   weekday     730 non-null    float64
 6   workingday  730 non-null    float64
 7   weathersit  730 non-null    float64
 8   temp        1218 non-null   float64
 9   atemp       1218 non-null   float64
 10  hum         1218 non-null   float64
 11  windspeed   1218 non-null   float64
 12  casual      730 non-null    float64
 13  registered  730 non-null    float64
 14  cnt         730 non-null    float64
dtypes: float64(14), object(1)
memory usage: 152.2+ KB

In [ ]:
df['count_2']= df['cnt'].apply(lambda x: x*2)

In [ ]:
df

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,count_2
instant,,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985,1970
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801,1602
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,2698
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,3124
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,3200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114,4228
727,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095,6190
728,29-12-2019,1,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341,2682
729,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796,3592
730,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729,5458

In [ ]:
df['s'] = df['dteday'].astype('str')+ ": " + df['cnt'].astype('str')

In [ ]:
df

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,count_2,s
instant,,,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985,1970,01-01-2018: 985
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801,1602,02-01-2018: 801
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,2698,03-01-2018: 1349
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,3124,04-01-2018: 1562
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,3200,05-01-2018: 1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114,4228,27-12-2019: 2114
727,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095,6190,28-12-2019: 3095
728,29-12-2019,1,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341,2682,29-12-2019: 1341
729,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796,3592,30-12-2019: 1796
730,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729,5458,31-12-2019: 2729

In [ ]:
df.drop(['count_2','s'],inplace=True,axis=1)

In [ ]:
df

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
727,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
728,29-12-2019,1,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
729,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
730,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

### `corr()` function explanation

-   **Purpose**: Calculates the correlation coefficient between numerical columns.
-   **Output**: Returns a correlation matrix, where each cell `(i, j)` represents the correlation between column `i` and column `j`.
-   **Methods**: By default, it uses Pearson correlation. Other methods like Kendall and Spearman can also be specified.

Let's see the correlation matrix for our `df` DataFrame:

In [ ]:
df.corr(numeric_only=True)

,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
season,1.000000e+00,-3.279074e-16,8.310321e-01,-0.010868,-0.003081,0.013762,0.021306,0.333361,0.342014,0.208220,-0.229607,0.208737,0.410310,0.404584
yr,-3.279074e-16,1.000000e+00,-5.162656e-16,0.008195,-0.005466,-0.002945,-0.050322,0.048789,0.047215,-0.112547,-0.011624,0.250502,0.596911,0.569728
mnth,8.310321e-01,-5.162656e-16,1.000000e+00,0.018905,0.009523,-0.004688,0.045613,0.219083,0.226430,0.224937,-0.208013,0.121208,0.291952,0.278191
holiday,-1.086804e-02,8.195345e-03,1.890483e-02,1.000000,-0.101962,-0.252948,-0.034395,-0.028764,-0.032703,-0.015662,0.006257,0.054055,-0.109142,-0.068764
weekday,-3.081198e-03,-5.466369e-03,9.522969e-03,-0.101962,1.000000,0.035800,0.031112,-0.000168,-0.007539,-0.052290,0.014283,0.059978,0.057427,0.067534
workingday,1.376178e-02,-2.945396e-03,-4.687953e-03,-0.252948,0.035800,1.000000,0.060236,0.053470,0.052940,0.023202,-0.018666,-0.517607,0.305437,0.062542
weathersit,2.130636e-02,-5.032247e-02,4.561335e-02,-0.034395,0.031112,0.060236,1.000000,-0.119503,-0.120559,0.590277,0.039769,-0.246044,-0.259025,-0.295929
temp,3.333607e-01,4.878919e-02,2.190833e-01,-0.028764,-0.000168,0.053470,-0.119503,1.000000,0.991696,0.128565,-0.158186,0.542731,0.539436,0.627044
atemp,3.420139e-01,4.721519e-02,2.264302e-01,-0.032703,-0.007539,0.052940,-0.120559,0.991696,1.000000,0.141512,-0.183876,0.543362,0.543678,0.630685
hum,2.082196e-01,-1.125471e-01,2.249368e-01,-0.015662,-0.052290,0.023202,0.590277,0.128565,0.141512,1.000000,-0.248506,-0.075211,-0.089212,-0.098543
windspeed,-2.296069e-01,-1.162435e-02,-2.080131e-01,0.006257,0.014283,-0.018666,0.039769,-0.158186,-0.183876,-0.248506,1.000000,-0.167995,-0.217914,-0.235132
casual,2.087373e-01,2.505017e-01,1.212079e-01,0.054055,0.059978,-0.517607,-0.246044,0.542731,0.543362,-0.075211,-0.167995,1.000000,0.394137,0.672123
registered,4.103102e-01,5.969106e-01,2.919516e-01,-0.109142,0.057427,0.305437,-0.259025,0.539436,0.543678,-0.089212,-0.217914,0.394137,1.000000,0.945411
cnt,4.045838e-01,5.697285e-01,2.781909e-01,-0.068764,0.067534,0.062542,-0.295929,0.627044,0.630685,-0.098543,-0.235132,0.672123,0.945411,1.000000

In [61]:
import numpy as np
data = {'birds': ['Cranes', 'Cranes', 'plovers', 'spoonbills', 'spoonbills', 'Cranes', 'plovers', 'Cranes', 'spoonbills', 'spoonbills'], 'age': [3.5, 4, 1.5, np.nan, 6, 3, 5.5, np.nan, 8, 4], 'visits': [2, 4, 3, 4, 3, 4, 2, 2, 3, 2], 'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

d = pd.DataFrame(data=data,index=labels)
d

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  NaN       4      yes
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

In [63]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   birds     10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes

In [64]:
d.head(2)

    birds  age  visits priority
a  Cranes  3.5       2      yes
b  Cranes  4.0       4      yes

In [65]:
d[['birds','age']]

        birds  age
a      Cranes  3.5
b      Cranes  4.0
c     plovers  1.5
d  spoonbills  NaN
e  spoonbills  6.0
f      Cranes  3.0
g     plovers  5.5
h      Cranes  NaN
i  spoonbills  8.0
j  spoonbills  4.0

In [69]:
 #select [2, 3, 7] rows and in columns ['birds', 'age', 'visits']
d.loc[['b','c','g'],['birds', 'age', 'visits']]

     birds  age  visits
b   Cranes  4.0       4
c  plovers  1.5       3
g  plovers  5.5       2

In [70]:
#select the rows where the number of visits is less than 4
d[d['visits']<4]

        birds  age  visits priority
a      Cranes  3.5       2      yes
c     plovers  1.5       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

In [77]:
d[np.isnan(d['age'])][['birds','visits']]

        birds  visits
d  spoonbills       4
h      Cranes       2

In [80]:
# Select the rows where the birds is a Cranes and the age is less than 4
d[d['birds']=='Cranes'][d['age']<4]

/tmp/ipykernel_18917/2259311388.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  d[d['birds']=='Cranes'][d['age']<4]

    birds  age  visits priority
a  Cranes  3.5       2      yes
f  Cranes  3.0       4       no

In [85]:
#Select the rows the age is between 2 and 4(inclusive)
d[(d['age'] >= 2) & (d['age'] <= 4)]

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
f      Cranes  3.0       4       no
j  spoonbills  4.0       2       no

In [86]:
#Find the total number of visits of the bird Cranes
d[d['birds']=='Cranes']['visits'].sum()

np.int64(12)

In [90]:
#Calculate the mean age for each different birds in dataframe.
d.groupby('birds')['age'].mean()

birds
Cranes        3.5
plovers       3.5
spoonbills    6.0
Name: age, dtype: float64

In [94]:
#Append a new row 'k' to dataframe with your choice of values for each column. Then delete that row to return the original DataFrame.
d['nw']=d['age'].apply(lambda x: x*2)
d.drop('nw',axis=1,inplace=True)
d

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  NaN       4      yes
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

In [96]:
#Find the number of each type of birds in dataframe (Counts)
d.groupby('birds').size()

birds
Cranes        4
plovers       2
spoonbills    4
dtype: int64

In [97]:
#Sort dataframe (birds) first by the values in the 'age' in decending order, then by the value in the 'visits' column in ascending order.
d.sort_values(by=['age','visits'],ascending=[False,True])

        birds  age  visits priority
i  spoonbills  8.0       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
j  spoonbills  4.0       2       no
b      Cranes  4.0       4      yes
a      Cranes  3.5       2      yes
f      Cranes  3.0       4       no
c     plovers  1.5       3       no
h      Cranes  NaN       2      yes
d  spoonbills  NaN       4      yes

In [100]:
 #Replace the priority column values with'yes' should be 1 and 'no' should be 0
d.loc[d['priority'] == 'yes', 'priority'] = 1
d.loc[d['priority'] == 'no', 'priority'] = 0
d

        birds  age  visits priority
a      Cranes  3.5       2        1
b      Cranes  4.0       4        1
c     plovers  1.5       3        0
d  spoonbills  NaN       4        1
e  spoonbills  6.0       3        0
f      Cranes  3.0       4        0
g     plovers  5.5       2        0
h      Cranes  NaN       2        1
i  spoonbills  8.0       3        0
j  spoonbills  4.0       2        0

In [103]:
#In the 'birds' column, change the 'Cranes' entries to 'trumpeters'.
d.loc[d['birds']=='Cranes','birds']='trumpeters'
d

        birds  age  visits priority
a  trumpeters  3.5       2        1
b  trumpeters  4.0       4        1
c     plovers  1.5       3        0
d  spoonbills  NaN       4        1
e  spoonbills  6.0       3        0
f  trumpeters  3.0       4        0
g     plovers  5.5       2        0
h  trumpeters  NaN       2        1
i  spoonbills  8.0       3        0
j  spoonbills  4.0       2        0